//
//  ClipboardManager.swift
//  DiskSync
//
//  Lightweight clipboard history: polls the general pasteboard's changeCount on
//  a slow timer and keeps the most recent text / image copies so they can be
//  re-copied with one click. Fully local.
//

import Foundation
import AppKit

nonisolated struct ClipItem: Identifiable, Sendable {
    enum Kind: Sendable { case text, image }
    let id = UUID()
    var kind: Kind
    var text: String?
    var imageData: Data?
    var date: Date
}

@MainActor
@Observable
final class ClipboardManager {
    static let shared = ClipboardManager()

    var items: [ClipItem] = []
    private let maxItems = 20
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: Timer?

    private init() { start() }

    private func start() {
        let timer = Timer(timeInterval: 1.0, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func poll() {
        guard Preferences.shared.clipboardEnabled else { return }
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        // Honor the convention password managers use to keep secrets/OTPs out of
        // clipboard history (concealed / transient / auto-generated).
        let secret: Set<NSPasteboard.PasteboardType> = [
            .init("org.nspasteboard.ConcealedType"),
            .init("org.nspasteboard.TransientType"),
            .init("org.nspasteboard.AutoGeneratedType"),
        ]
        if let types = pb.types, !Set(types).isDisjoint(with: secret) { return }
        capture(pb)
    }

    private func capture(_ pb: NSPasteboard) {
        if let string = pb.string(forType: .string), !string.isEmpty {
            // Skip consecutive duplicates.
            if items.first?.text == string { return }
            prepend(ClipItem(kind: .text, text: string, imageData: nil, date: Date()))
        } else if let png = imageAsPNG(pb) {
            prepend(ClipItem(kind: .image, text: nil, imageData: png, date: Date()))
        }
    }

    /// Always store images as PNG so re-copying doesn't mislabel TIFF bytes.
    private func imageAsPNG(_ pb: NSPasteboard) -> Data? {
        if let png = pb.data(forType: .png) { return png }
        if let tiff = pb.data(forType: .tiff) {
            return NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
        }
        return nil
    }

    private func prepend(_ item: ClipItem) {
        items.insert(item, at: 0)
        if items.count > maxItems { items = Array(items.prefix(maxItems)) }
    }

    /// Put an item back on the pasteboard (and bump our own change marker so we
    /// don't immediately re-capture it as new).
    func copyToPasteboard(_ item: ClipItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text:
            if let text = item.text { pb.setString(text, forType: .string) }
        case .image:
            if let data = item.imageData { pb.setData(data, forType: .png) }
        }
        lastChangeCount = pb.changeCount
    }

    func remove(_ item: ClipItem) { items.removeAll { $0.id == item.id } }
    func clear() { items.removeAll() }
}
